// <auto-generated />
using System;
using Book.Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book.API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230723153349_initialMigration2")]
    partial class initialMigration2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book.Data.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoryType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e2e344e8-4f49-4595-ac05-47fcd779382b"),
                            CategoryType = 6,
                            CreatedDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4031),
                            IsDeleted = false,
                            Name = "Cemile",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0e3a5b02-05d3-4f59-a45a-2a5f7cedf725"),
                            CategoryType = 6,
                            CreatedDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4046),
                            IsDeleted = false,
                            Name = "Toprak Ana",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d5affa3a-1fc4-4750-ad4e-0c52b8612497"),
                            CategoryType = 5,
                            CreatedDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4048),
                            IsDeleted = false,
                            Name = "Puslu Kıtalar Atlası",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("cb63e0f5-1290-41ad-ac69-1959cb1a8ee8"),
                            CategoryType = 2,
                            CreatedDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4050),
                            IsDeleted = false,
                            Name = "Tahıla Karsı",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Book.Data.Entities.Checkouts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("Checkouts", (string)null);
                });

            modelBuilder.Entity("Book.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d16f6c48-1529-472a-9d03-918209117875"),
                            CreatedDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4232),
                            Name = "Admin",
                            Password = "1234",
                            SignUpDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4233),
                            Token = "",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserType = 0
                        },
                        new
                        {
                            Id = new Guid("d9a7c9b9-48f7-422f-9be6-97d9e08303c8"),
                            CreatedDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4237),
                            Name = "umutulupinar",
                            Password = "1234",
                            SignUpDate = new DateTime(2023, 7, 23, 18, 33, 49, 427, DateTimeKind.Local).AddTicks(4237),
                            Token = "",
                            UpdatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserType = 1
                        });
                });

            modelBuilder.Entity("Book.Data.Entities.Checkouts", b =>
                {
                    b.HasOne("Book.Data.Entities.Book", "Book")
                        .WithMany("Checkouts")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Book.Data.Entities.User", "User")
                        .WithMany("Checkouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Book.Data.Entities.Book", b =>
                {
                    b.Navigation("Checkouts");
                });

            modelBuilder.Entity("Book.Data.Entities.User", b =>
                {
                    b.Navigation("Checkouts");
                });
#pragma warning restore 612, 618
        }
    }
}
